### ISSUE TITLE
difference between  const eta_format_length and the real length sometime

### ISSUE THREAD

**Issue by Saverio976** [Waqar144/progressbar#4]
(on Windows and Linux)

If ProgessBarTime have one of its attribute > 10, the final length or the eta print at the end of each line is different than the const, 
it result of a an issue for the carriage return (\r) :  
- the line is no longer clear, 
- and a new line appear (with the progressbar update). 
This happen until the format_eta length match the eta_format_length const
![image](https://user-images.githubusercontent.com/57769503/121774117-f913aa00-cb80-11eb-8843-0dd173ede689.png)

how did you want to solve this ? 
- make one extra 0 all time for seconds, minutes ?
- or use the final format_eta.len instead of the const eta_format_length
- or another solution that you have ?

(I can do that but just want to know how you want the progessbar will be)

**Comment by Waqar144** [comment]
Since I am quite out of touch with this, feel free to change it whatever you think is better.

**Comment by Saverio976** [comment]
The latest merge solve this "issue"
